[[actions]]
atype = "1"
x = "1199"
y = "319"

[[actions]]
atype = "0"
x = "0"
y = "0"

[[actions]]
atype = "0"
x = "0"
y = "0"

[[actions]]
atype = "0"
x = "0"
y = "0"

[[actions]]
atype = "0"
x = "0"
y = "0"

[[actions]]
atype = "0"
x = "0"
y = "0"

[[actions]]
atype = "0"
x = "0"
y = "0"

[[actions]]
atype = "0"
x = "0"
y = "0"

[config]
block_height_half = "28"
block_width_half = "25"
bufferHeight = "70"
gravity_y = "2000"
height = "390"
player_height_half = "21"
player_width_half = "25"
preparation_width = "1200"
speed_x = "340"
speed_y = "700"
spike_height_half = "20"
spike_width_half = "25"

[[objects]]
btype = "1"
x = "200"
y = "0"

[[objects]]
btype = "0"
x = "0"
y = "0"

[[objects]]
btype = "0"
x = "0"
y = "0"
