[[actions]]
atype = ""
x = ""
y = ""

[[actions]]
atype = ""
x = ""
y = ""

[[actions]]
atype = ""
x = ""
y = ""

[[actions]]
atype = ""
x = ""
y = ""

[[actions]]
atype = ""
x = ""
y = ""

[[actions]]
atype = ""
x = ""
y = ""

[[actions]]
atype = ""
x = ""
y = ""

[[actions]]
atype = ""
x = ""
y = ""

[config]
bufferHeight = ""
gravity_y = ""
height = ""
preparation_width = ""
speed_x = ""
speed_y = ""

[[objects]]
btype = ""
x = ""
y = ""

[[objects]]
btype = ""
x = ""
y = ""

[[objects]]
btype = ""
x = ""
y = ""
